# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "Danforth Restorative"
tagline:          'A Jekyll theme'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://danforth-restorative.com/
baseurl:          ''

author:
  name:           'David Danforth'
  url:            https://twitter.com/DavidDanforth12

paginate:         5
paginate_path:    '/blog/page:num'
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
