# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "David Danforth"
tagline:          'Restorative Practice'
description:      'Personal Blog and Restorative Practice: Nonviolence, Anti-Racism, Anti-Sexism; Personal Growth, Emotional and Spiritual Development.'
url:              https://danforth-restorative.com
baseurl:          ''

image: /assets/images/Danforth-Restorative-og_MAKY_OREL.png

author:
  name:           'David Danforth'
  url:            https://twitter.com/DavidDanforth12
  picture:        '/assets/images/dand.jpg'

paginate:         5
paginate_path:    '/blog/page:num'
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

# Sidebar link settings
# sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      comments: FALSE
      image: /assets/images/Danforth-Restorative-og_MAKY_OREL.png