name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
env:
  INTL: 'no' # 'yes' if internationalization extensions are required
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.2-cli-alpine
    steps:
    - name: Install PHP extensions
      if: env.INTL == 'yes'
      run: |
        apk update
        apk add --no-cache gettext-dev icu-dev
        docker-php-ext-install -j$(nproc) gettext
        docker-php-ext-install -j$(nproc) intl
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install theme(s)
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --prefer-dist --no-dev --no-progress --no-interaction
    - name: Build site with Cecil
      env:
        CECIL_VERSION: '5.28.1'
        CECIL_BASEURL: '/'
      run: |
        if [[ -z "$CECIL_VERSION" ]]; then
          echo "### Downloading Cecil"
          curl -sSOL https://cecil.app/cecil.phar
        else
          echo "### Downloading Cecil $CECIL_VERSION"
          curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
        fi
        echo "### Building Cecil static site"
        php cecil.phar build -v
        echo "### Cecil Action done"
    - name: Deploy Changes
      run: |
        git remote add gh-token "https://github.com/danforth-restorative/website.git"
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull
        git commit -a -m "build site"
        git push gh-token master
